micronaut:
  application:
    name: easeci-worker
  server:
    port: 9001

easeci:
  worker-node:
    name: ${WORKER_NODE_NAME:default}
    id: ${random.uuid}
    ip: ${WORKER_NODE_IP:127.0.0.1}
    transfer-protocol: ${WORKER_NODE_TRANSFER_PROTOCOL:HTTPS}
    port: ${WORKER_NODE_PORT:9001}
    domain-name: ${WORKER_NODE_DOMAIN_NAME:}
docker:
  base-image:
    resources-path: "dockerfiles/Dockerfile_base_image"
    repository: debian
    tag: stable-slim
    produced-tag: easeci-worker-base-platform:1.0.0
  predefined_images:
    - name: "easeci-default"
      repository: "easeci-worker-base-platform"
      tag: "1.0.0"
      resources-path: "dockerfiles/Dockerfile_base_image"
    - name: "easeci-java-17"
      repository: "easeci-java-17"
      tag: "1.0.0"
      resources-path: "dockerfiles/Dockerfile_java_17"
