micronaut:
  application:
    name: easeci-worker
  server:
    port: 9001

easeci:
  worker-node:
    name: ${WORKER_NODE_NAME:default}
    id: ${random.uuid}
    ip: ${WORKER_NODE_IP:127.0.0.1}
    transfer-protocol: ${WORKER_NODE_TRANSFER_PROTOCOL:HTTPS}
    port: ${WORKER_NODE_PORT:9001}
    domain-name: ${WORKER_NODE_DOMAIN_NAME:}
docker:
  base-image:
    resources-path: "dockerfiles/BaseImageDockerfile"
    repository: debian
    tag: stable-slim
    produced-tag: easeci-worker-base-platform:1.0.0
    pipeline-processing-image: easeci-worker-base-platform:1.0.0
